services:
  jenkins:
    user: root
    image: "jenkins/jenkins:lts"
    ports:
      - "8080:8080"
    volumes:
      - jenkins-home:/var/jenkins_home
      #- /usr/local/bin/docker:/usr/bin/docker
      #- /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins-home:
